site_name: RecreioHelp!
site_author: Iago Viana
site_description: Um site com o objetivo de responder e ajudar os alunos do Campus Recreio.

copyright: Copyright &copy; 2020 <a href="https://twitter.com/Iabo_Vastier" target="_blank" rel="external">Iago Viana</a>

nav:
  - Início: index.md
  - Guias: guias.md
  # Implementar depois:
  #
  # - Perguntas Frequentes: faq.md
  # - Boas Vindas, Calouros!: calouros.md
  # - Sobre: sobre.md
  # - infodump.md


theme: 
  name: darkly
  custom_dir: custom_theme/

plugins:
  - search:
      lang: pt
      separator: '[\s]+' # Separa os termos por espaços.
